server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}


service:
  jwt:
    secret-key: ${JWT_SECRET}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}