server:
  port: ${GATEWAY_PORT:19000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:19090/eureka}


service:
  jwt:
    secret-key: ${JWT_SECRET}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
