spring:
  application:
    name: gateway-service

  # local 환경 실행 기분
  profiles:
    default: local

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
          #User Service
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
          # Hub Service
            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/api/v1/hubs/**

          # Company Service
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**

          # Product Service
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**


          # Order Service
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

          # Delivery Service
            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**

          # Notification Service
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/ai-alerts/**
                - Path=/api/v1/slack-messages/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/api/v1/deliveries/**, /api/v1/delivery-managers/**

        discovery:
          locator:
            enabled: true


