server:
  port: ${ORDER_SERVICE_PORT:19005}

spring:
  application:
    name: order-service

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_schema

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: ${FEIGN_CONNECT_TIMEOUT:3000}
            read-timeout: ${FEIGN_READ_TIMEOUT:5000}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:19090/eureka}
